version: "3.9"

services:
  zookeeper:
    image: "zookeeper:3.7.0"
    restart: "always"

  kafka:
    image: "wurstmeister/kafka:2.13-2.8.1"
    hostname: "localhost"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  postgres:
    image: "postgres:14.1-alpine"
    environment:
      POSTGRES_PASSWORD: "changeme"
    ports:
      - "5432:5432"
