version: "3.9"

services:
  isitup-producer:
    build:
      dockerfile: "Dockerfile.producer"
      context: "."
    container_name: "isitup-producer-prod"
    restart: "always"
    environment:
      ISITUP_CONFIG_FILE: "config.prod.yml"

  isitup-consumer:
    build:
      dockerfile: "Dockerfile.consumer"
      context: "."
    container_name: "isitup-consumer-prod"
    restart: "always"
    environment:
      ISITUP_CONFIG_FILE: "config.prod.yml"
