version: "3.9"

services:
  zookeeper:
    image: "zookeeper:3.7.0"
    container_name: "zookeeper"
    # Always restart, as per Zookeeper documentation
    restart: "always"
    networks:
      - "kafka-conn"

  kafka:
    image: "wurstmeister/kafka:2.13-2.8.1"
    container_name: "kafka"
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_BROKER_ID: "1"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    networks:
      - "kafka-conn"

  postgres:
    image: "postgres:14.1-alpine"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: "changeme"
    ports:
      - "5432:5432"
    networks:
      - "db-conn"

  isitup-producer-dev:
    build:
      dockerfile: "Dockerfile.producer"
      context: "."
    restart: "always"
    environment:
      ISITUP_CONFIG_FILE: "config.dev.yml"
    depends_on:
      - "kafka"
    networks:
      - "kafka-conn"

  isitup-consumer-dev:
    build:
      dockerfile: "Dockerfile.consumer"
      context: "."
    restart: "always"
    environment:
      ISITUP_CONFIG_FILE: "config.dev.yml"
    depends_on:
      - "kafka"
      - "postgres"
    networks:
      - "kafka-conn"
      - "db-conn"

networks:
  kafka-conn:
    driver: bridge
  db-conn:
    driver: bridge
